
cc_library(
    name = "class",
    srcs = ["fraction.cpp",
            "matrix.cpp",
            "row.cpp",
            "list.inl", 
            ],
    hdrs = ["fraction.hpp",
            "matrix.hpp",
            "row.hpp",
            "list.hpp",
    ],
    visibility = ["//visibility:public"]
)
