
cc_library(
    name = "StudentAfterFirstSesion",
    srcs = ["StudentAfterFirstSesion.cpp"],
    hdrs = ["StudentAfterFirstSesion.hpp"],
    deps = ["//src/class/Student:Student"],
    visibility = ["//visibility:public"]
)
