
cc_library(
    name = "StudentAfterSecondSesion",
    srcs = ["StudentAfterSecondSesion.cpp"],
    hdrs = ["StudentAfterSecondSesion.hpp"],
    deps = ["//src/class/StudentAfterFirstSesion:StudentAfterFirstSesion"],
    visibility = ["//visibility:public"]
)
