
cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    data = ["//src/resource:Info"],
    deps = ["//src/task-2:task-2", "//src/task-3:task-3", "//src/task-4:task-4", "//src/task-5:task-5", "//src/task-6:task-6"]
)
