
cc_library(
    name = "class",
    deps = ["//src/class/Student:Student",
            "//src/class/StudentAfterFirstSesion:StudentAfterFirstSesion",
            "//src/class/StudentAfterSecondSesion:StudentAfterSecondSesion"
            ],
    visibility = ["//visibility:public"]
)
