
cc_library(
    name = "Forest",
    srcs = ["Forest.cpp"],
    hdrs = ["Forest.hpp"],
    deps = ["//src/class/FruitTree:FruitTree",
            "//src/class/ForestTree:ForestTree",
            "//src/class/Tree:Tree"
            ],

    visibility = ["//visibility:public"]
)
